<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Recovery.Core\Recovery.Core.csproj" />
    <ProjectReference Include="..\Recovery.OsuApi\Recovery.OsuApi.csproj" />
    <ProjectReference Include="..\Recovery.Downloads\Recovery.Downloads.csproj" />
    <ProjectReference Include="..\Recovery.Packaging\Recovery.Packaging.csproj" />
    <ProjectReference Include="..\Recovery.Import\Recovery.Import.csproj" />
    <ProjectReference Include="..\Recovery.Local\Recovery.Local.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\OsuRecoverLibrary.ico</ApplicationIcon>
    <AssemblyName>Osu_Library_Recovery</AssemblyName>
    <Product>Osu_Library_Recovery Application</Product>
    <AssemblyTitle>Osu_Library_Recovery Application</AssemblyTitle>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
